services:
  - type: web
    plan: free
    name: TN
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn ser:app & bash start.sh 
    region: frankfurt #frankfurt #Singapore
    envVars:
      - key: APP_ID 
        value: 9514755
      - key: API_HASH 
        value: 40e7041d06ea7b6ee1cf39b3188b3452
